# Generated by Django 5.2 on 2025-04-24 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgHeader', models.CharField(max_length=100)),
                ('imgLink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PapersAndPresentations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('courseGrade', models.CharField(max_length=3)),
                ('fileLink', models.CharField(max_length=100)),
                ('courseCodefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='portfolio_app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projTitle', models.CharField(max_length=100)),
                ('courseGrade', models.CharField(max_length=3)),
                ('sourceCodeRepo', models.CharField(max_length=200)),
                ('projDescription', models.TextField()),
                ('projCompileInfo', models.TextField()),
                ('projUiInfo', models.TextField()),
                ('projAddConsiderations', models.TextField(max_length=2500)),
                ('courseCodefk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio_app.course')),
            ],
        ),
    ]
