# Generated by Django 5.2 on 2025-04-24 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_projectimages_papersandpresentations_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUIImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_images', to='portfolio_app.projectimages')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_images', to='portfolio_app.projects')),
            ],
        ),
    ]
