# Generated by Django 5.2 on 2025-04-24 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_projectuiimages'),
    ]

    operations = [
    ]
