# Generated by Django 5.2 on 2025-04-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_auto_20250424_1843'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
        migrations.AlterModelOptions(
            name='projectuiimages',
            options={'ordering': ['projectID']},
        ),
        migrations.RenameField(
            model_name='papersandpresentations',
            old_name='courseCodefk',
            new_name='courseCode',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='courseCodefk',
            new_name='courseCode',
        ),
        migrations.AddField(
            model_name='projectuiimages',
            name='figureNum',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='projectuiimages',
            unique_together={('projectID', 'figureNum')},
        ),
    ]
