# Generated by Django 5.2 on 2025-04-24 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0006_alter_courses_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='papersandpresentations',
            options={'verbose_name': 'Paper or Presentation', 'verbose_name_plural': 'Papers and Presentations'},
        ),
        migrations.AlterModelOptions(
            name='projectimages',
            options={'verbose_name': 'Project Image', 'verbose_name_plural': 'Project Images'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='projectuiimages',
            options={'ordering': ['projectID'], 'verbose_name': 'Project UI Image', 'verbose_name_plural': 'Project UI Images'},
        ),
    ]
