# Generated by Django 5.2 on 2025-04-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0007_alter_papersandpresentations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projThumbnail',
            field=models.CharField(default='placeholder', max_length=200),
            preserve_default=False,
        ),
    ]
