# Generated by Django 5.2 on 2025-04-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0008_projects_projthumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='papersandpresentations',
            name='type',
            field=models.CharField(default='Presentation', max_length=30),
            preserve_default=False,
        ),
    ]
