# Generated by Django 5.2 on 2025-04-27 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0009_papersandpresentations_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectuiimages',
            options={'ordering': ['projectInfoID'], 'verbose_name': 'Project UI Image', 'verbose_name_plural': 'Project UI Images'},
        ),
        migrations.RemoveField(
            model_name='projects',
            name='projAddConsiderations',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='projCompileInfo',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='projDescription',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='projUiInfo',
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projDescription', models.TextField()),
                ('projCompileInfo', models.TextField()),
                ('projUiInfo', models.TextField()),
                ('projAddConsiderations', models.TextField()),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_info', to='portfolio_app.projects')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='projectuiimages',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='projectuiimages',
            name='projectInfoID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ui_images', to='portfolio_app.projectinfo'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='projectuiimages',
            unique_together={('projectInfoID', 'figureNum')},
        ),
        migrations.RemoveField(
            model_name='projectuiimages',
            name='projectID',
        ),
    ]
