# Generated by Django 5.2 on 2025-04-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0010_alter_projectuiimages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projectType',
            field=models.CharField(default='School', max_length=30),
            preserve_default=False,
        ),
    ]
