# Generated by Django 5.2 on 2025-04-27 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0011_projects_projecttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLanguages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='portfolio_app.languages')),
                ('projectID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='portfolio_app.projects')),
            ],
        ),
    ]
