# Generated by Django 5.2 on 2025-04-27 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0012_languages_projectlanguages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectlanguages',
            name='languageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='portfolio_app.languages'),
        ),
    ]
