# Generated by Django 5.2 on 2025-04-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0013_alter_projectlanguages_languageid'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='projLanguages',
            field=models.ManyToManyField(to='portfolio_app.languages'),
        ),
    ]
