# Generated by Django 5.2 on 2025-04-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0014_projects_projlanguages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuiimages',
            name='imagesID',
        ),
        migrations.RemoveField(
            model_name='projectlanguages',
            name='languageID',
        ),
        migrations.RemoveField(
            model_name='projectlanguages',
            name='projectID',
        ),
        migrations.AddField(
            model_name='projectuiimages',
            name='imgHeader',
            field=models.CharField(default='fig', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectuiimages',
            name='imgLink',
            field=models.CharField(default='placeholder', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
        migrations.DeleteModel(
            name='ProjectLanguages',
        ),
    ]
